version: "2"

services:
  postgres:
    image: postgres:9.4
    volumes:
      - "./build/data/postgres:/var/lib/postgresql/data"
      - "./build/logs/postgres:/var/log"
    environment:
      POSTGRES_USER:     aleph
      POSTGRES_PASSWORD: aleph
      POSTGRES_DATABASE: aleph

  elasticsearch:
    image: elasticsearch:2.2.0
    volumes:
      - "./build/data/elasticsearch:/usr/share/elasticsearch/data"
      - "./build/logs/elasticsearch:/var/log"

  rabbitmq:
    image: rabbitmq
    volumes:
      - "./build/data/rabbitmq:/var/lib/rabbitmq"
      - "./build/logs/rabbitmq:/var/log"

  ## If you enable Tika, also set ALEPH_TIKA_URI=http://tika:9998 on the
  ## worker and web containers.
  # tika:
  #   image: logicalspark/docker-tikaserver

  worker:
      build: .
      command: celery -A aleph.queues -B -c 4 -l INFO worker --pidfile /var/lib/celery.pid
      links:
        - postgres
        - elasticsearch
        - rabbitmq
      volumes:
        - "./build/logs/worker:/var/log"
        - "./build/archive:/archive"
        - "./build/incoming:/incoming"
        - "./build/polyglot:/polyglot"
      environment:
        C_FORCE_ROOT: 'true'
        ALEPH_ELASTICSEARCH_URI: http://elasticsearch:9200/
        ALEPH_DATABASE_URI: postgresql://aleph:aleph@postgres/aleph
        ALEPH_BROKER_URI: amqp://guest:guest@rabbitmq:5672
        ALEPH_ARCHIVE_PATH: /archive
        POLYGLOT_DATA_PATH: /polyglot
      env_file:
        - aleph.env

  beat:
      build: .
      command: celery -A aleph.queues beat -s /var/lib/celerybeat-schedule.db --pidfile /var/lib/celery.pid
      links:
        - postgres
        - elasticsearch
        - rabbitmq
      volumes:
        - "./build/logs/beat:/var/log"
        - "./build/data/beat:/var/lib/"
        - "./build/archive:/archive"
        - "./build/polyglot:/polyglot"
      environment:
        C_FORCE_ROOT: 'true'
        ALEPH_ELASTICSEARCH_URI: http://elasticsearch:9200/
        ALEPH_DATABASE_URI: postgresql://aleph:aleph@postgres/aleph
        ALEPH_BROKER_URI: amqp://guest:guest@rabbitmq:5672
        ALEPH_ARCHIVE_PATH: /archive
        POLYGLOT_DATA_PATH: /polyglot
      env_file:
        - aleph.env

  web:
      build: .
      command: gunicorn -w 5 -b 0.0.0.0:8000 --log-level info --log-file /var/log/gunicorn.log aleph.manage:app
      ports:
        - "13376:8000"
      links:
        - postgres
        - elasticsearch
        - rabbitmq
      volumes:
        - "./build/logs/web:/var/log"
        - "./build/archive:/archive"
        - "./build/polyglot:/polyglot"
      environment:
        ALEPH_ELASTICSEARCH_URI: http://elasticsearch:9200/
        ALEPH_DATABASE_URI: postgresql://aleph:aleph@postgres/aleph
        ALEPH_BROKER_URI: amqp://guest:guest@rabbitmq:5672
        ALEPH_ARCHIVE_PATH: /archive
        POLYGLOT_DATA_PATH: /polyglot
      env_file:
        - aleph.env
