version: "2"

services:
  resolvable:
    image: mgood/resolvable
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
      - "/etc/resolv.conf:/tmp/resolv.conf"

  postgres:
    image: postgres:9.4
    volumes:
      - "./build/data/postgres:/var/lib/postgresql/data"
      - "./build/logs/postgres:/var/log"
    environment:
      POSTGRES_USER:     aleph
      POSTGRES_PASSWORD: aleph
      POSTGRES_DATABASE: aleph
    ports:
     - "127.0.0.1:5439:5432"

  elasticsearch:
    image: elasticsearch:2.2.0
    volumes:
      - "./build/data/elasticsearch:/usr/share/elasticsearch/data"
      - "./build/logs/elasticsearch:/var/log"
    ports:
      - "127.0.0.1:9201:9209"

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672

  # neo4j:
  #   image: neo4j:3.0
  #   volumes:
  #     - "/opt/aleph/data/neo4j:/data"
  #   ports:
  #     - 7474
  #     - 7687
    volumes:
      - "./build/data/rabbitmq:/var/lib/rabbitmq"
      - "./build/logs/rabbitmq:/var/log"

  worker:
      image: alephdata/aleph:latest
      command: make worker
      links:
        - postgres
        - elasticsearch
        - rabbitmq
      volumes:
        - "/:/host"
        - "./build/archive:/data"
        - "./build/logs/worker:/var/log"
        - "./build/polyglot:/polyglot"
        - "./:/aleph"

      environment:
        C_FORCE_ROOT: 'true'
        ALEPH_ELASTICSEARCH_URI: http://elasticsearch:9200/
        ALEPH_DATABASE_URI: postgresql://aleph:aleph@postgres/aleph
        ALEPH_BROKER_URI: amqp://guest:guest@rabbitmq:5672
        POLYGLOT_DATA_PATH: /polyglot
      env_file:
        - aleph.env

  beat:
      image: alephdata/aleph:latest
      command: make beat
      links:
        - postgres
        - elasticsearch
        - rabbitmq
      volumes:
        - "./build/logs/beat:/var/log"
        - "./build/run/beat:/var/run"
        - "./build/polyglot:/polyglot"
        - "./build/archive:/data"
        - "./build/polyglot:/polyglot"
        - "./:/aleph"

      environment:
        C_FORCE_ROOT: 'true'
        ALEPH_ELASTICSEARCH_URI: http://elasticsearch:9200/
        ALEPH_DATABASE_URI: postgresql://aleph:aleph@postgres/aleph
        ALEPH_BROKER_URI: amqp://guest:guest@rabbitmq:5672
        POLYGLOT_DATA_PATH: /polyglot
      env_file:
        - aleph.env

  app:
      image: alephdata/aleph:latest
      command: make web
      ports:
        - "13376:8000"
      links:
        - postgres
        - elasticsearch
        - rabbitmq
      volumes:
        - "./build/logs/web:/var/log"
        - "./build/archive:/data"
        - "./build/polyglot:/polyglot"
        - "./:/aleph"

      environment:
        C_FORCE_ROOT: 'true'
        ALEPH_ELASTICSEARCH_URI: http://elasticsearch:9200/
        ALEPH_DATABASE_URI: postgresql://aleph:aleph@postgres/aleph
        ALEPH_BROKER_URI: amqp://guest:guest@rabbitmq:5672
        POLYGLOT_DATA_PATH: /polyglot
      env_file:
        - aleph.env
