datasets:
  ofac:
    label: OFAC Specially Designated Nationals
    info_url: https://www.treasury.gov/resource-center/sanctions/SDN-List/Pages/sdn_data.aspx
    category: sanctions
    roles:
      - guest
    queries:
      - csv_url: https://docs.google.com/spreadsheets/d/1thC2m9-jGkyAC1NyyUHaM51lszmgpMK5sx-vmoWk0Kc/pub?gid=97991589&single=true&output=csv
        filters:
          sdn_type: individual
        entities:
          person:
            schema: Person
            keys:
              - sdn_name
              - ent_num
            properties:
              name:
                column: sdn_name
              position:
                column: title
              notes:
                column: remarks
              program:
                column: program
      - csv_url: https://docs.google.com/spreadsheets/d/1thC2m9-jGkyAC1NyyUHaM51lszmgpMK5sx-vmoWk0Kc/pub?gid=97991589&single=true&output=csv
        filters_not:
          sdn_type: vessel
          sdn_type: individual
        entities:
          entity:
            schema: LegalEntity
            keys:
              - sdn_name
              - ent_num
            properties:
              name:
                column: sdn_name
              notes:
                column: remarks
              program:
                column: program
      - csv_url: https://docs.google.com/spreadsheets/d/1thC2m9-jGkyAC1NyyUHaM51lszmgpMK5sx-vmoWk0Kc/pub?gid=97991589&single=true&output=csv
        filters:
          sdn_type: vessel
        entities:
          vessel:
            schema: Vessel
            keys:
              - call_sign
              - ent_num
            properties:
              name:
                column: sdn_name
              notes:
                column: remarks
              program:
                column: program
              callSign:
                column: call_sign
              type:
                column: vess_type
              tonnage:
                column: tonnage
              grossRegisteredTonnage:
                column: grt
              flag:
                column: vess_flag
          owner:
            schema: LegalEntity
            key: vess_owner
            key_fingerprint: true
            properties:
              name:
                column: vess_owner
        links:
          - schema: ownedBy
            source: vessel
            target: owner
